# Generated by Django 6.0.3 on 2026-05-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_juegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
