# Generated by Django 6.0.3 on 2026-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_juegos', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor')], default='CLIENTE', max_length=10),
        ),
    ]
