# Generated by Django 6.0.3 on 2026-06-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_juegos', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
