# Generated by Django 6.0.3 on 2026-09-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_juegos', '0005_user_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_genre',
            field=models.BooleanField(default=False),
        ),
    ]
